import { BasicStrategyTestCase } from "../basic-strategy.test";
import { card, Rank } from "../card";
import { Move } from "../hand";

export const S17WithSurrenderCases: BasicStrategyTestCase[] = [
  {
    name: "hard 16 vs 9 → surrender",
    cards: [card(Rank.Seven), card(Rank.Nine)],
    dealerCard: card(Rank.Nine),
    expected: Move.Surrender,
  },
  {
    name: "hard 16 vs 10 → surrender",
    cards: [card(Rank.Six), card(Rank.Ten)],
    dealerCard: card(Rank.Ten),
    expected: Move.Surrender,
  },
  {
    name: "hard 16 vs A → surrender",
    cards: [card(Rank.Six), card(Rank.Queen)],
    dealerCard: card(Rank.Ace),
    expected: Move.Surrender,
  },
  {
    name: "hard 15 vs 10 → surrender",
    cards: [card(Rank.Nine), card(Rank.Six)],
    dealerCard: card(Rank.Ten),
    expected: Move.Surrender,
  },
  {
    name: "hard 15 vs J → surrender",
    cards: [card(Rank.Nine), card(Rank.Six)],
    dealerCard: card(Rank.Jack),
    expected: Move.Surrender,
  },
  {
    name: "hard 15 vs A → hit",
    cards: [card(Rank.Nine), card(Rank.Six)],
    dealerCard: card(Rank.Ace),
    expected: Move.Hit,
  },
  {
    name: "hard 17 vs 5 → stand",
    cards: [card(Rank.Nine), card(Rank.Eight)],
    dealerCard: card(Rank.Five),
    expected: Move.Stand,
  },
  {
    name: "hard 13 vs 2 → stand",
    cards: [card(Rank.Seven), card(Rank.Six)],
    dealerCard: card(Rank.Two),
    expected: Move.Stand,
  },
  {
    name: "hard 11 vs 4 → double or hit",
    cards: [card(Rank.Two), card(Rank.Two), card(Rank.Seven)],
    dealerCard: card(Rank.Four),
    expected: Move.DoubleOrHit,
  },
  {
    name: "hard 11 vs 5 → double or hit",
    cards: [card(Rank.Two), card(Rank.Four), card(Rank.Five)],
    dealerCard: card(Rank.Five),
    expected: Move.DoubleOrHit,
  },
  {
    name: "hard 8 vs 10 → hit",
    cards: [card(Rank.Two), card(Rank.Two), card(Rank.Two), card(Rank.Two)],
    dealerCard: card(Rank.Ten),
    expected: Move.Hit,
  },
  {
    name: "hard 12 vs 3 → hit",
    cards: [card(Rank.Two), card(Rank.Two), card(Rank.Eight)],
    dealerCard: card(Rank.Three),
    expected: Move.Hit,
  },
  {
    name: "hard 12 vs 2 → hit",
    cards: [card(Rank.Two), card(Rank.Four), card(Rank.Six)],
    dealerCard: card(Rank.Two),
    expected: Move.Hit,
  },
  {
    name: "soft 17 vs 3 → double or hit",
    cards: [card(Rank.Ace), card(Rank.Six)],
    dealerCard: card(Rank.Three),
    expected: Move.DoubleOrHit,
  },
  {
    name: "soft 18 vs 2 → double or stand",
    cards: [card(Rank.Ace), card(Rank.Seven)],
    dealerCard: card(Rank.Two),
    expected: Move.DoubleOrStand,
  },
  {
    name: "soft 18 vs 9 → hit",
    cards: [card(Rank.Ace), card(Rank.Seven)],
    dealerCard: card(Rank.Nine),
    expected: Move.Hit,
  },
  {
    name: "soft 20 vs 3 → stand",
    cards: [card(Rank.Ace), card(Rank.Seven), card(Rank.Two)],
    dealerCard: card(Rank.Three),
    expected: Move.Stand,
  },
  {
    name: "soft 13 vs 6 → double or hit",
    cards: [card(Rank.Ace), card(Rank.Two)],
    dealerCard: card(Rank.Six),
    expected: Move.DoubleOrHit,
  },
  {
    name: "soft 14 vs 5 → double or hit",
    cards: [card(Rank.Ace), card(Rank.Three)],
    dealerCard: card(Rank.Five),
    expected: Move.DoubleOrHit,
  },
  {
    name: "soft 15 vs 6 → double or hit",
    cards: [card(Rank.Ace), card(Rank.Four)],
    dealerCard: card(Rank.Six),
    expected: Move.DoubleOrHit,
  },
  {
    name: "soft 16 vs 4 → double or hit",
    cards: [card(Rank.Ace), card(Rank.Five)],
    dealerCard: card(Rank.Four),
    expected: Move.DoubleOrHit,
  },
  {
    name: "soft 19 vs 6 → double or stand",
    cards: [card(Rank.Ace), card(Rank.Two), card(Rank.Two), card(Rank.Four)],
    dealerCard: card(Rank.Six),
    expected: Move.DoubleOrStand,
  },
  {
    name: "pair A vs K → split",
    cards: [card(Rank.Ace), card(Rank.Ace)],
    dealerCard: card(Rank.King),
    expected: Move.Split,
  },
  {
    name: "pair 8s vs K → split",
    cards: [card(Rank.Eight), card(Rank.Eight)],
    dealerCard: card(Rank.King),
    expected: Move.Split,
  },
  {
    name: "pair 10s vs 7 → stand",
    cards: [card(Rank.Ten), card(Rank.Ten)],
    dealerCard: card(Rank.Seven),
    expected: Move.Stand,
  },
  {
    name: "pair 9s vs 6 → split",
    cards: [card(Rank.Nine), card(Rank.Nine)],
    dealerCard: card(Rank.Six),
    expected: Move.Split,
  },
  {
    name: "pair 7s vs 8 → hit",
    cards: [card(Rank.Seven), card(Rank.Seven)],
    dealerCard: card(Rank.Eight),
    expected: Move.Hit,
  },
  {
    name: "pair 5s vs 6 → double or hit",
    cards: [card(Rank.Five), card(Rank.Five)],
    dealerCard: card(Rank.Six),
    expected: Move.DoubleOrHit,
  },
  {
    name: "pair 4s vs 5 → split",
    cards: [card(Rank.Four), card(Rank.Four)],
    dealerCard: card(Rank.Five),
    expected: Move.Split,
  },
  {
    name: "pair 4s vs 10 → hit",
    cards: [card(Rank.Four), card(Rank.Four)],
    dealerCard: card(Rank.Ten),
    expected: Move.Hit,
  },
  {
    name: "pair 2s vs 6 → split",
    cards: [card(Rank.Two), card(Rank.Two)],
    dealerCard: card(Rank.Six),
    expected: Move.Split,
  },
];
