import { BasicStrategyTestCase } from "../testUtils";
import { card, Rank } from "../card";
import { Move } from "../basicStrategy";

export const S17NoSurrenderCases: BasicStrategyTestCase[] = [
  {
    name: "hard 4 vs 2 → split",
    hand: [card(Rank.Two), card(Rank.Two)],
    dealerCard: card(Rank.Two),
    expected: Move.Split,
  },
  {
    name: "hard 4 vs 6 → split",
    hand: [card(Rank.Two), card(Rank.Two)],
    dealerCard: card(Rank.Six),
    expected: Move.Split,
  },
  {
    name: "hard 13 vs 6 → stand",
    hand: [card(Rank.Seven), card(Rank.Six)],
    dealerCard: card(Rank.Six),
    expected: Move.Stand,
  },
  {
    name: "hard 14 vs 7 → hit",
    hand: [card(Rank.Two), card(Rank.Four), card(Rank.Eight)],
    dealerCard: card(Rank.Seven),
    expected: Move.Hit,
  },
  {
    name: "hard 15 vs 9 → hit",
    hand: [card(Rank.Five), card(Rank.Five), card(Rank.Five)],
    dealerCard: card(Rank.Nine),
    expected: Move.Hit,
  },
  {
    name: "hard 16 vs 6 → stand",
    hand: [card(Rank.Nine), card(Rank.Seven)],
    dealerCard: card(Rank.Six),
    expected: Move.Stand,
  },
  {
    name: "hard 17 vs 5 → stand",
    hand: [card(Rank.Nine), card(Rank.Eight)],
    dealerCard: card(Rank.Five),
    expected: Move.Stand,
  },
  {
    name: "hard 18 vs 3 → split",
    hand: [card(Rank.Nine), card(Rank.Nine)],
    dealerCard: card(Rank.Three),
    expected: Move.Split,
  },
  {
    name: "hard 19 vs 10 → stand",
    hand: [card(Rank.King), card(Rank.Nine)],
    dealerCard: card(Rank.Ten),
    expected: Move.Stand,
  },
  {
    name: "hard 20 vs A → stand",
    hand: [card(Rank.King), card(Rank.Ten)],
    dealerCard: card(Rank.Ace),
    expected: Move.Stand,
  },
  {
    name: "hard 10 vs 9 with three cards → double or hit",
    hand: [card(Rank.Four), card(Rank.Three), card(Rank.Three)],
    dealerCard: card(Rank.Nine),
    expected: Move.DoubleOrHit,
  },
  {
    name: "hard 11 vs K with three cards → double or hit",
    hand: [card(Rank.Two), card(Rank.Three), card(Rank.Six)],
    dealerCard: card(Rank.King),
    expected: Move.DoubleOrHit,
  },
  {
    name: "soft 13 vs 6 → double or hit",
    hand: [card(Rank.Ace), card(Rank.Two)],
    dealerCard: card(Rank.Six),
    expected: Move.DoubleOrHit,
  },
  {
    name: "soft 13 vs 7 → hit",
    hand: [card(Rank.Ace), card(Rank.Two)],
    dealerCard: card(Rank.Seven),
    expected: Move.Hit,
  },
  {
    name: "soft 14 vs 5 → double or hit",
    hand: [card(Rank.Ace), card(Rank.Three)],
    dealerCard: card(Rank.Five),
    expected: Move.DoubleOrHit,
  },
  {
    name: "soft 15 vs 6 → double or hit",
    hand: [card(Rank.Ace), card(Rank.Four)],
    dealerCard: card(Rank.Six),
    expected: Move.DoubleOrHit,
  },
  {
    name: "soft 16 vs 4 → double or hit",
    hand: [card(Rank.Ace), card(Rank.Five)],
    dealerCard: card(Rank.Four),
    expected: Move.DoubleOrHit,
  },
  {
    name: "soft 17 vs 3 → double or hit",
    hand: [card(Rank.Ace), card(Rank.Six)],
    dealerCard: card(Rank.Three),
    expected: Move.DoubleOrHit,
  },
  {
    name: "soft 17 vs 7 → hit",
    hand: [card(Rank.Ace), card(Rank.Six)],
    dealerCard: card(Rank.Seven),
    expected: Move.Hit,
  },
  {
    name: "soft 18 vs 2 → double or stand",
    hand: [card(Rank.Ace), card(Rank.Seven)],
    dealerCard: card(Rank.Two),
    expected: Move.DoubleOrStand,
  },
  {
    name: "soft 18 vs 9 → hit",
    hand: [card(Rank.Ace), card(Rank.Seven)],
    dealerCard: card(Rank.Nine),
    expected: Move.Hit,
  },
  {
    name: "soft 20 vs 3 → stand",
    hand: [card(Rank.Ace), card(Rank.Seven), card(Rank.Two)],
    dealerCard: card(Rank.Three),
    expected: Move.Stand,
  },
  {
    name: "soft 19 vs 6 → double or stand",
    hand: [card(Rank.Ace), card(Rank.Three), card(Rank.Five)],
    dealerCard: card(Rank.Six),
    expected: Move.DoubleOrStand,
  },
  {
    name: "soft 19 vs 6 with four cards → double or stand",
    hand: [card(Rank.Ace), card(Rank.Two), card(Rank.Two), card(Rank.Four)],
    dealerCard: card(Rank.Six),
    expected: Move.DoubleOrStand,
  },
  {
    name: "pair A vs K → split",
    hand: [card(Rank.Ace), card(Rank.Ace)],
    dealerCard: card(Rank.King),
    expected: Move.Split,
  },
  {
    name: "pair 8s vs K → split",
    hand: [card(Rank.Eight), card(Rank.Eight)],
    dealerCard: card(Rank.King),
    expected: Move.Split,
  },
  {
    name: "pair 10s vs 7 → stand",
    hand: [card(Rank.Ten), card(Rank.Ten)],
    dealerCard: card(Rank.Seven),
    expected: Move.Stand,
  },
  {
    name: "pair 9s vs 7 → stand",
    hand: [card(Rank.Nine), card(Rank.Nine)],
    dealerCard: card(Rank.Seven),
    expected: Move.Stand,
  },
  {
    name: "pair 9s vs 6 → split",
    hand: [card(Rank.Nine), card(Rank.Nine)],
    dealerCard: card(Rank.Six),
    expected: Move.Split,
  },
  {
    name: "pair 7s vs 8 → hit",
    hand: [card(Rank.Seven), card(Rank.Seven)],
    dealerCard: card(Rank.Eight),
    expected: Move.Hit,
  },
  {
    name: "pair 6s vs 7 → hit",
    hand: [card(Rank.Six), card(Rank.Six)],
    dealerCard: card(Rank.Seven),
    expected: Move.Hit,
  },
  {
    name: "pair 5s vs 6 → double or hit",
    hand: [card(Rank.Five), card(Rank.Five)],
    dealerCard: card(Rank.Six),
    expected: Move.DoubleOrHit,
  },
  {
    name: "pair 4s vs 5 → split",
    hand: [card(Rank.Four), card(Rank.Four)],
    dealerCard: card(Rank.Five),
    expected: Move.Split,
  },
  {
    name: "pair 4s vs 10 → hit",
    hand: [card(Rank.Four), card(Rank.Four)],
    dealerCard: card(Rank.Ten),
    expected: Move.Hit,
  },
  {
    name: "pair 2s vs 6 → split",
    hand: [card(Rank.Two), card(Rank.Two)],
    dealerCard: card(Rank.Six),
    expected: Move.Split,
  },
  {
    name: "pair 3s vs 8 → hit",
    hand: [card(Rank.Three), card(Rank.Three)],
    dealerCard: card(Rank.Eight),
    expected: Move.Hit,
  },
];
